name             'role-mongodb-replicaset2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-replicaset2'
long_description 'Installs/Configures role-mongodb-replicaset2'
version          '0.1.1'

depends 'mongodb', '0.16.2'
depends 'yum'
