name             'role-mongodb-replicaset2'
maintainer       'Stephen Van Zee'
maintainer_email 'svanzee@aringbridge.org'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-replicaset2'
long_description 'Installs/Configures role-mongodb-replicaset2'
version          '0.1.1'

depends 'mongodb', '0.16.2'
depends 'yum'
